services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.10"
      ONLINE_MODE: "false"
      DIFFICULTY: "2"
      LEVEL: "PirxWorld"
      TZ: "Europe/Kiev"
      LOG_TIMESTAMP: "true"
      ENABLE_WHITELIST: "true"
      WHITELIST: |-
        mrPrivik_123
        Pirx
    volumes:
      - ./data:/data
